# Site settings
title: "Ray Storer"
description: "My github resume"

# Build settings
markdown: kramdown
# remote_theme: rwstorer/resume
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar: "true"
resume_name: "Raymond W. Storer III"
resume_title: "Active Directory Administrator"

# used for the contact button in _layouts/resume.html
resume_contact_email: "raymond.storer@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone: "send emails please"
resume_contact_address: "send emails please"

resume_header_contact_info: "send emails please"
display_header_contact_info: "false"

resume_header_intro: "<p>Senior technical team leader with strong experience in enterprise deployments of both hardware and software. Strong skills in automating repetitive tasks.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work: "no"

# Decide which sections to use
# comment out to hide
resume_section_experience: "true"
resume_section_education: "true"
resume_section_projects: "false"
resume_section_skills: "true"
resume_section_recognition: "true"
resume_section_links: "true"
resume_section_associations: "false"
resume_section_interests: "true"

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url: "https://github.com/rwstorer/"
  resume_twitter_url: "http://twitter.com/rwstorer"
  #resume_dribbble_url: "insert dribbble URL here"
  # resume_facebook_url: "insert Facebook URL here"
  resume_linkedin_url: "https://www.linkedin.com/in/rwstorer"
  # resume_instagram_url: "insert your Instagram URL here"
  resume_website_url: "http://rwstorer.github.io/resume/"
  #resume_medium_url:  "medium.com URL"
resume_print_social_links: "true"

# Design settings
resume_theme: "default"

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
